apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" .Values.songs.name }}
  namespace: {{ required "namespace is required!" .Values.namespace }}
spec:
  selector:
    app: {{ .Values.songs.name}}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30001
  type: NodePort
