apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-db-service" .Values.resources.name }}
  namespace: {{ required "namespace is required!" .Values.namespace }}
spec:
  selector:
    app: {{ printf "%s-db" .Values.resources.name }}
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
