apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-deployment" .Values.resources.name }}
  labels:
    app: {{ .Values.resources.name }}
  namespace: {{ required "namespace is required!" .Values.namespace }}
spec:
  replicas: {{ .Values.resources.deployment.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.resources.name }}
  template:
    metadata:
      name: {{ .Values.resources.name }}
      labels:
        app: {{ .Values.resources.name }}
      namespace: {{ required "namespace is required!" .Values.namespace }}
    spec:
      containers:
        - name: {{ .Values.resources.name }}
          image: resources-image:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: RESOURCES_DB_URL
              value: {{ printf "%s-db-service" .Values.resources.name }}
            - name: RESOURCES_DB_PORT
              value: "5432"
          ports:
            - containerPort: 8080
              protocol: TCP
          startupProbe:
            httpGet:
              port: 8080
              path: /actuator/health
            failureThreshold: 30
            timeoutSeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/liveness
            initialDelaySeconds: 15
            periodSeconds: 10
            failureThreshold: 3
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              port: 8080
              path: /actuator/health/readiness
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 10
      restartPolicy: Always
