apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-service" .Values.resources.name }}
  namespace: {{ required "namespace is required!" .Values.namespace }}
spec:
  selector:
    app: {{ .Values.resources.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
